display_name: Clash for Flutter
icon: assets/icon.png
generic_name: Clash Application
categories:
  - Network
  - Science
  - Development
  - System
keywords:
  - Clash
  - Flutter
  - Application
startup_notify: true
include: []
