app_id: B3039CF4-E394-42B6-971C-4BE97F322DE8
publisher: mapleafgo
publisher_url: https://github.com/mapleafgo/clash-for-flutter
display_name: Clash for Flutter
create_desktop_icon: true
install_dir_name: ClashForFlutter
